"""Render the two TRX exercises as posed human figures, in the dataset's visual language.

Run headless (Blender 4.2+; developed on 5.2):
    blender --background --python scripts/render-trx-media.py -- <out_dir>
then assemble the GIFs with:
    python3 scripts/build-trx-gif.py <out_dir> frontend/src/assets/trx

The figure is generated by MPFB2 (https://extensions.blender.org/add-ons/mpfb/), whose
bundled assets and generated content are CC0. The add-on is installed on first run from the
zip named below; drop the zip beside this script or pass MPFB_ZIP in the environment.

Posing is physical rather than keyframed. For the push-up the body is rigid and pivots about
the feet on the bench while the hands stay on the handles, so the elbow bend falls out of the
IK. For the leg curl the hips ride up on a spine bend while the ankle targets travel towards
them, so the knee fold falls out of the same solver. Each exercise renders 12 frames: the two
end positions and five eased steps between them, matching the dataset's cadence.

The scene deliberately carries no floor and no anchor bar — the dataset isolates its figures
on white, and the extra geometry only competed with the movement at 180 px.
"""
import bpy
import math
import os
import sys
import addon_utils
from mathutils import Vector

ARGS = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
OUT = (ARGS[0] if ARGS else "/tmp/trx").rstrip("/")
MPFB_ZIP = os.environ.get(
    "MPFB_ZIP", os.path.join(os.path.dirname(os.path.abspath(__file__)), "mpfb.zip"))
RES = 360                       # 2x; build-trx-gif.py downsamples to the dataset's 180
BAR_Z = 2.25                    # straps run up to here and leave the frame

SKIN = (0.80, 0.80, 0.80)
GEAR = (0.38, 0.38, 0.38)
PROP = (0.90, 0.90, 0.90)


def ease(t):
    return 0.5 - 0.5 * math.cos(math.pi * t)


def ensure_mpfb():
    mod = "bl_ext.user_default.mpfb"
    if any(m.__name__ == mod for m in addon_utils.modules()):
        addon_utils.enable(mod, default_set=True)
        return
    if not os.path.exists(MPFB_ZIP):
        sys.exit(f"MPFB2 zip not found at {MPFB_ZIP}. Download the add-on from "
                 "https://extensions.blender.org/add-ons/mpfb/ or set MPFB_ZIP.")
    bpy.ops.extensions.package_install_files(
        filepath=MPFB_ZIP, repo="user_default", enable_on_install=True)


def clear():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def flat(name, rgb):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    b = m.node_tree.nodes["Principled BSDF"]
    b.inputs["Base Color"].default_value = (*rgb, 1.0)
    b.inputs["Roughness"].default_value = 0.9
    if "Specular IOR Level" in b.inputs:
        b.inputs["Specular IOR Level"].default_value = 0.05
    return m


def cube(loc, scale, material):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=loc)
    o = bpy.context.object
    o.scale = scale
    o.data.materials.append(material)
    return o


def cylinder(p1, p2, r, material):
    a, b = Vector(p1), Vector(p2)
    d = b - a
    bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=r, depth=d.length,
                                        location=(a + b) / 2)
    o = bpy.context.object
    o.rotation_euler = d.to_track_quat("Z", "Y").to_euler()
    o.data.materials.append(material)
    return o


def spawn_human(skin, location, euler):
    """A fresh MPFB2 human, rigged, hung off an empty so the whole body can be placed."""
    bpy.ops.mpfb.create_human()
    human = bpy.data.objects["Human"]
    human.data.materials.clear()
    human.data.materials.append(skin)
    bpy.context.view_layer.objects.active = human
    human.select_set(True)
    bpy.ops.mpfb.add_standard_rig()
    rig = bpy.data.objects["Human.rig"]
    pivot = bpy.data.objects.new("pivot", None)
    bpy.context.collection.objects.link(pivot)
    pivot.location = location
    pivot.rotation_mode = "YXZ"
    pivot.rotation_euler = euler
    for o in (human, rig):
        o.parent = pivot
        o.matrix_parent_inverse = pivot.matrix_world.inverted()
    return rig


def ik(rig, bone, target, chain=4):
    pb = rig.pose.bones.get(bone)
    if pb:
        c = pb.constraints.new("IK")
        c.target = target
        c.chain_count = chain


def empty(name, location):
    e = bpy.data.objects.new(name, None)
    bpy.context.collection.objects.link(e)
    e.location = location
    return e


# ------------------------------------------------------------------ push-up
PU_FOOT_X = -0.75
PU_BENCH_TOP = 0.45
PU_HAND = Vector((0.62, 0.0, 0.12))
PU_INCLINE = (10.0, 34.0)
PU_CAM = dict(az=26.0, elev=24.0, dist=6.0, target=(0.0, 0.45), ortho=1.95, pitch=66.0)


def build_pushup(t, skin, gear, prop):
    cube((PU_FOOT_X - 0.28, 0, PU_BENCH_TOP / 2), (0.62, 0.7, PU_BENCH_TOP), prop)
    inc = math.radians(PU_INCLINE[0] + (PU_INCLINE[1] - PU_INCLINE[0]) * t)
    rig = spawn_human(skin, (PU_FOOT_X, 0.0, PU_BENCH_TOP),
                      (math.radians(90), math.radians(90) + inc, 0))
    for side, dy in (("L", 0.30), ("R", -0.30)):
        e = empty(f"hand.{side}", PU_HAND + Vector((0, dy, 0)))
        ik(rig, f"lowerarm02.{side}", e)
        cylinder((e.location.x, e.location.y, BAR_Z), e.location, 0.012, gear)
        cylinder((e.location.x, e.location.y - 0.07, e.location.z),
                 (e.location.x, e.location.y + 0.07, e.location.z), 0.022, gear)


# ----------------------------------------------------------------- leg curl
LC_CRADLE_Z = 0.34
LC_ANKLE_X = (-0.56, -0.10)
LC_BRIDGE = (13.0, 22.0)
LC_SPINE = ("spine05", "spine04", "spine03", "spine02", "spine01")
LC_CAM = dict(az=26.0, elev=20.0, dist=6.0, target=(0.2, 0.30), ortho=1.95, pitch=70.0)


def build_legcurl(t, skin, gear, prop):
    rig = spawn_human(skin, (-0.62, 0.0, 0.10),
                      (math.radians(-90), math.radians(90), 0))
    bend = math.radians(LC_BRIDGE[0] + (LC_BRIDGE[1] - LC_BRIDGE[0]) * t)
    for name in LC_SPINE:
        pb = rig.pose.bones.get(name)
        if pb:
            pb.rotation_mode = "XYZ"
            pb.rotation_euler.rotate_axis("X", bend / len(LC_SPINE))
    ax = LC_ANKLE_X[0] + (LC_ANKLE_X[1] - LC_ANKLE_X[0]) * t
    for side, dy in (("L", 0.12), ("R", -0.12)):
        e = empty(f"ankle.{side}", Vector((ax, dy, LC_CRADLE_Z)))
        ik(rig, f"lowerleg02.{side}", e)
        cylinder((LC_ANKLE_X[0], dy, BAR_Z), e.location, 0.012, gear)
        cylinder((e.location.x, dy - 0.05, e.location.z - 0.03),
                 (e.location.x, dy + 0.05, e.location.z - 0.03), 0.02, gear)


# -------------------------------------------------------------------- render
def setup_render(cam_cfg):
    scn = bpy.context.scene
    scn.render.engine = "BLENDER_EEVEE"
    scn.render.resolution_x = scn.render.resolution_y = RES
    # Without Standard the default view transform tone-maps white down to mid grey, and the
    # dataset's flat white ground would come out as a grey card.
    scn.view_settings.view_transform = "Standard"
    scn.view_settings.look = "None"
    scn.world = bpy.data.worlds.new("W")
    scn.world.use_nodes = True
    bg = scn.world.node_tree.nodes["Background"]
    bg.inputs[0].default_value = (1, 1, 1, 1)
    bg.inputs[1].default_value = 1.0

    az, elev = math.radians(cam_cfg["az"]), math.radians(cam_cfg["elev"])
    d = cam_cfg["dist"]
    tx, tz = cam_cfg["target"]
    bpy.ops.object.camera_add(location=(tx + d * math.sin(az) * math.cos(elev),
                                        -d * math.cos(az) * math.cos(elev),
                                        tz + d * math.sin(elev)))
    cam = bpy.context.object
    cam.data.type = "ORTHO"
    cam.data.ortho_scale = cam_cfg["ortho"]
    cam.rotation_euler = (math.radians(cam_cfg["pitch"]), 0, cam_cfg["az"] * math.pi / 180)
    scn.camera = cam

    bpy.ops.object.light_add(type="SUN", location=(-2, -6, 5))
    bpy.context.object.data.energy = 2.4
    bpy.context.object.rotation_euler = (math.radians(50), 0, math.radians(30))

    scn.render.use_freestyle = True
    vl = bpy.context.view_layer
    vl.use_freestyle = True
    fs = vl.freestyle_settings
    ls = fs.linesets.new("outline") if not fs.linesets else fs.linesets[0]
    ls.select_silhouette = True
    ls.select_border = True
    ls.select_crease = False
    style = bpy.data.linestyles.new("outline")
    ls.linestyle = style
    style.color = (0.15, 0.15, 0.15)
    style.thickness = 1.8


def render_set(builder, cam_cfg, stem):
    os.makedirs(OUT, exist_ok=True)
    for i in range(12):
        t = ease(i / 6 if i <= 6 else (12 - i) / 6)
        clear()
        setup_render(cam_cfg)
        builder(t, flat("skin", SKIN), flat("gear", GEAR), flat("prop", PROP))
        bpy.context.view_layer.update()
        bpy.context.scene.render.filepath = f"{OUT}/{stem}_{i:02d}.png"
        bpy.ops.render.render(write_still=True)
    print(f"OK {stem}: 12 frames -> {OUT}")


ensure_mpfb()
render_set(build_pushup, PU_CAM, "9001")
render_set(build_legcurl, LC_CAM, "9002")
